schema_version: 1

context:
  name: octree-creation-app
  version: 0.3.0a1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: b3359c7b3333a3208fa78c4f114eae8b5be0b256ece51aa4b9d14b5f2998bf3b
  path: ../${{ name }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10.0,<4.0.0
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=3.10.0,<3.11
    - discretize >=0.10.0,<0.11.0
    - numpy >=1.26.0,<1.27.0
    - scipy >=1.14.0,<1.15.0
    - geoh5py >=0.11.0a1,<0.12.0a.dev
    - geoapps-utils >=0.5.0a1,<0.6.0a.dev
    - h5py >=3.2.1,<4.0.0
    - pillow >=10.3.0,<10.4.0
    - pydantic >=2.5.2,<2.6.0

about:
  summary: Octree creation app.
  description: |
    The octree-creation-app package lets users create Octree mesh objects with local
    refinements using the SimPEG.discretize package. The refinements can be performed
    on any number of Objects stored in a geoh5 file.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/octree-creation-app
  documentation: https://mirageoscience-octree-creation-app.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg

