name: Deploy python package in development

on:
  push:
    tags:
      - 'v*' # Push events to every tag not containing

jobs:
  call-workflow-conda-publish:
    name: Publish development conda package on JFrog Artifactory
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-publish_conda_package.yml@DEVOPS-504
    with:
      package-name: 'octree-creation-app'
      python-version: '3.10'
      repo-names: '["public-conda-dev-local"]'
    secrets:
      JFROG_ARTIFACTORY_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
      JFROG_ARTIFACTORY_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
